SmartMenu: com.uperto.smartmenu.SmartMenuOverlayView Class Reference
com.uperto.smartmenu.SmartMenuOverlayView Class Reference
Inherits android::gesture::GestureOverlayView, and android::gesture::GestureOverlayView::OnGesturePerformedListener.
Classes
class SmartMenuCircleView
class SmartMenuIconFactory
class SmartMenuItem
Public Member Functions
SmartMenuOverlayView (Context context)
SmartMenuOverlayView (Context context, AttributeSet attributes)
GestureLibrary getGestureLibrary ()
void setGestureLibrary (GestureLibrary library)
void addMenuItem (SmartMenuItem item)
SmartMenuItem getMenuItem (int index)
boolean deleteMenuItem (SmartMenuItem item)
void insertMenuItemAt (SmartMenuItem item, int index)
int indexOf (SmartMenuItem item)
void setPainter (Paint painter)
Paint getPainter ()
void setBackgroundColor (int color)
boolean displayHalo ()
void setDisplayHalo (boolean displayHalo)
int getHaloRadius ()
void setHaloRadius (int radius)
int getHaloGradient ()
void setHaloGradient (int gradient)
int getHaloCenterColor ()
void setHaloCenterColor (int color)
int getHaloOutsideColor ()
void setHaloOutsideColor (int color)
void open (boolean animate)
void close ()
boolean isOpened ()
void onGesturePerformed (GestureOverlayView overlay, Gesture gesture)
Protected Attributes
boolean mDisplayHalo = true
int mHaloRadius = 30
int mHaloGradient = 15
int mHaloCenterColor = Color.argb(100, 128, 128, 128)
int mHaloOutsideColor = Color.argb(10, 255, 255, 255)
Static Protected Attributes
static int sCenterRadius = 32
static int sBranchesLength = 24
static int sBranchesRadius = 24
static int sCircleSpeed = 30
static int sLineSpeed = 10
static int sLabelMargin = 10
static int sLabelHeight = 50
static int sLabelWidth = 200
static int sLabelFont = 30
static final double RAD_45 = Math.PI/4
static final double COS_45 = Math.cos(RAD_45)
static final double SIN_45 = Math.sin(RAD_45)
Private Member Functions
void init (Context context)
Private Attributes
SmartMenuCircleView mCircleView
GestureLibrary mLibrary
Detailed Description
Definition at line 41 of file SmartMenuOverlayView.java.
Constructor & Destructor Documentation
com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuOverlayView (Context context)
Parameters:
context
Definition at line 79 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.init().
com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuOverlayView (Context context, AttributeSet attributes)
Parameters:
context
attributes
Definition at line 88 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.init().
Member Function Documentation
void com.uperto.smartmenu.SmartMenuOverlayView.addMenuItem (SmartMenuItem item)
Add an item to the menu No more than 8 items can be used
Parameters:
item
Definition at line 127 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.addMenuItem(), and com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
void com.uperto.smartmenu.SmartMenuOverlayView.close ()
Close the circle menu if opened
Definition at line 278 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.close(), and com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
boolean com.uperto.smartmenu.SmartMenuOverlayView.deleteMenuItem (SmartMenuItem item)
Parameters:
item
Returns:
Definition at line 143 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.deleteMenuItem(), and com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
boolean com.uperto.smartmenu.SmartMenuOverlayView.displayHalo ()
Returns:
is the halo enabled
Definition at line 190 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mDisplayHalo.
GestureLibrary com.uperto.smartmenu.SmartMenuOverlayView.getGestureLibrary ()
Get the associated gesture library
Returns:
A gesture library, or null
Definition at line 109 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mLibrary.
int com.uperto.smartmenu.SmartMenuOverlayView.getHaloCenterColor ()
Returns:
the color of the center of the halo
Definition at line 234 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloCenterColor.
int com.uperto.smartmenu.SmartMenuOverlayView.getHaloGradient ()
Returns:
the number of steps used to draw the halo
Definition at line 218 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloGradient.
int com.uperto.smartmenu.SmartMenuOverlayView.getHaloOutsideColor ()
Returns:
the color of the outline border of the halo
Definition at line 248 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloOutsideColor.
int com.uperto.smartmenu.SmartMenuOverlayView.getHaloRadius ()
Returns:
the halo radius
Definition at line 204 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloRadius.
SmartMenuItem com.uperto.smartmenu.SmartMenuOverlayView.getMenuItem (int index)
Parameters:
index
Returns:
Definition at line 135 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.getMenuItem(), and com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
Paint com.uperto.smartmenu.SmartMenuOverlayView.getPainter ()
Get the painter used to draw the menu
Returns:
Definition at line 176 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mCircleView, and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mPainter.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
int com.uperto.smartmenu.SmartMenuOverlayView.indexOf (SmartMenuItem item)
Parameters:
item
Returns:
Definition at line 159 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.indexOf(), and com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
void com.uperto.smartmenu.SmartMenuOverlayView.init (Context context) [private]
Called by all the constructors
Parameters:
context
Definition at line 97 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuOverlayView().
void com.uperto.smartmenu.SmartMenuOverlayView.insertMenuItemAt (SmartMenuItem item, int index)
Parameters:
item
index
Definition at line 151 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.insertMenuItemAt(), and com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
boolean com.uperto.smartmenu.SmartMenuOverlayView.isOpened ()
Returns:
true if the circle menu is visible
Definition at line 285 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
void com.uperto.smartmenu.SmartMenuOverlayView.onGesturePerformed (GestureOverlayView overlay, Gesture gesture)
Definition at line 290 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mLibrary, and com.uperto.smartmenu.SmartMenuOverlayView.open().
void com.uperto.smartmenu.SmartMenuOverlayView.open (boolean animate)
Parameters:
animate If true, skip the opening animation
Definition at line 262 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mCircleView, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.reset(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setAnimationEnd().
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate(), and com.uperto.smartmenu.SmartMenuOverlayView.onGesturePerformed().
void com.uperto.smartmenu.SmartMenuOverlayView.setBackgroundColor (int color)
Definition at line 183 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mCircleView.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.init(), and com.uperto.smartmenu.SmartMenuActivity.onCreate().
void com.uperto.smartmenu.SmartMenuOverlayView.setDisplayHalo (boolean displayHalo)
Parameters:
displayHalo true to display the halo, false to hide it
Definition at line 197 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mDisplayHalo.
void com.uperto.smartmenu.SmartMenuOverlayView.setGestureLibrary (GestureLibrary library)
Define the gesture library used for the menu opening Any gesture contained in this library will open the menu
Parameters:
library
Definition at line 118 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mLibrary.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
void com.uperto.smartmenu.SmartMenuOverlayView.setHaloCenterColor (int color)
Parameters:
color the color of the center of the halo
Definition at line 241 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloCenterColor.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
void com.uperto.smartmenu.SmartMenuOverlayView.setHaloGradient (int gradient)
The more steps we use, the more smooth is the halo gradient Using more steps than the radius is useless
Parameters:
gradient the number of steps used to draw the halo
Definition at line 227 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloGradient.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
void com.uperto.smartmenu.SmartMenuOverlayView.setHaloOutsideColor (int color)
Parameters:
color the color of the outline border of the halo
Definition at line 255 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloOutsideColor.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
void com.uperto.smartmenu.SmartMenuOverlayView.setHaloRadius (int radius)
Parameters:
radius the halo radius to set
Definition at line 211 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloRadius.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
void com.uperto.smartmenu.SmartMenuOverlayView.setPainter (Paint painter)
Set the painter used to draw the menu If no painter is set, a default painter will be used
Parameters:
painter
Definition at line 168 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mCircleView, and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mPainter.
Member Data Documentation
final double com.uperto.smartmenu.SmartMenuOverlayView.COS_45 = Math.cos(RAD_45) [static, protected]
Definition at line 70 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch().
SmartMenuCircleView com.uperto.smartmenu.SmartMenuOverlayView.mCircleView [private]
Definition at line 73 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.addMenuItem(), com.uperto.smartmenu.SmartMenuOverlayView.close(), com.uperto.smartmenu.SmartMenuOverlayView.deleteMenuItem(), com.uperto.smartmenu.SmartMenuOverlayView.getMenuItem(), com.uperto.smartmenu.SmartMenuOverlayView.getPainter(), com.uperto.smartmenu.SmartMenuOverlayView.indexOf(), com.uperto.smartmenu.SmartMenuOverlayView.init(), com.uperto.smartmenu.SmartMenuOverlayView.insertMenuItemAt(), com.uperto.smartmenu.SmartMenuOverlayView.isOpened(), com.uperto.smartmenu.SmartMenuOverlayView.open(), com.uperto.smartmenu.SmartMenuOverlayView.setBackgroundColor(), and com.uperto.smartmenu.SmartMenuOverlayView.setPainter().
boolean com.uperto.smartmenu.SmartMenuOverlayView.mDisplayHalo = true [protected]
Definition at line 59 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.displayHalo(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), and com.uperto.smartmenu.SmartMenuOverlayView.setDisplayHalo().
int com.uperto.smartmenu.SmartMenuOverlayView.mHaloCenterColor = Color.argb(100, 128, 128, 128) [protected]
Definition at line 65 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo(), com.uperto.smartmenu.SmartMenuOverlayView.getHaloCenterColor(), and com.uperto.smartmenu.SmartMenuOverlayView.setHaloCenterColor().
int com.uperto.smartmenu.SmartMenuOverlayView.mHaloGradient = 15 [protected]
Definition at line 63 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo(), com.uperto.smartmenu.SmartMenuOverlayView.getHaloGradient(), and com.uperto.smartmenu.SmartMenuOverlayView.setHaloGradient().
int com.uperto.smartmenu.SmartMenuOverlayView.mHaloOutsideColor = Color.argb(10, 255, 255, 255) [protected]
Definition at line 66 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo(), com.uperto.smartmenu.SmartMenuOverlayView.getHaloOutsideColor(), and com.uperto.smartmenu.SmartMenuOverlayView.setHaloOutsideColor().
int com.uperto.smartmenu.SmartMenuOverlayView.mHaloRadius = 30 [protected]
Definition at line 62 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo(), com.uperto.smartmenu.SmartMenuOverlayView.getHaloRadius(), and com.uperto.smartmenu.SmartMenuOverlayView.setHaloRadius().
GestureLibrary com.uperto.smartmenu.SmartMenuOverlayView.mLibrary [private]
Definition at line 74 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.getGestureLibrary(), com.uperto.smartmenu.SmartMenuOverlayView.onGesturePerformed(), and com.uperto.smartmenu.SmartMenuOverlayView.setGestureLibrary().
final double com.uperto.smartmenu.SmartMenuOverlayView.RAD_45 = Math.PI/4 [static, protected]
Definition at line 69 of file SmartMenuOverlayView.java.
int com.uperto.smartmenu.SmartMenuOverlayView.sBranchesLength = 24 [static, protected]
Definition at line 44 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
int com.uperto.smartmenu.SmartMenuOverlayView.sBranchesRadius = 24 [static, protected]
Definition at line 46 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuIconFactory.createRoundedBitmap(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent().
int com.uperto.smartmenu.SmartMenuOverlayView.sCenterRadius = 32 [static, protected]
Definition at line 43 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
int com.uperto.smartmenu.SmartMenuOverlayView.sCircleSpeed = 30 [static, protected]
Definition at line 49 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
final double com.uperto.smartmenu.SmartMenuOverlayView.SIN_45 = Math.sin(RAD_45) [static, protected]
Definition at line 71 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch().
int com.uperto.smartmenu.SmartMenuOverlayView.sLabelFont = 30 [static, protected]
Definition at line 56 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawLabel(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
int com.uperto.smartmenu.SmartMenuOverlayView.sLabelHeight = 50 [static, protected]
Definition at line 54 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawLabel(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
int com.uperto.smartmenu.SmartMenuOverlayView.sLabelMargin = 10 [static, protected]
Definition at line 53 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawLabel(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
int com.uperto.smartmenu.SmartMenuOverlayView.sLabelWidth = 200 [static, protected]
Definition at line 55 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawLabel(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
int com.uperto.smartmenu.SmartMenuOverlayView.sLineSpeed = 10 [static, protected]
Definition at line 50 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
The documentation for this class was generated from the following file:
src/com/uperto/smartmenu/SmartMenuOverlayView.java