SmartMenu: com.uperto.smartmenu.SmartMenuActivity Class Reference
com.uperto.smartmenu.SmartMenuActivity Class Reference
Inherits android::app::Activity.
Public Member Functions
void onCreate (Bundle savedInstanceState)
Protected Member Functions
void onSaveInstanceState (Bundle outState)
Private Attributes
GestureLibrary mLibrary
TextView mText
Button mButton1
Button mButton2
boolean mChangedBackgroundColor = false
boolean mChangedPainterColor = false
boolean mChangedPainterStrokeWidth = false
boolean mChangedHaloCenterColor = false
boolean mChangedHaloOutsideColor = false
boolean mChangedHaloGradient = false
boolean mChangedHaloRadius = false
Detailed Description
Definition at line 32 of file SmartMenuActivity.java.
Member Function Documentation
void com.uperto.smartmenu.SmartMenuActivity.onCreate (Bundle savedInstanceState)
Called when the activity is first created.
Definition at line 49 of file SmartMenuActivity.java.
References com.uperto.smartmenu.SmartMenuOverlayView.addMenuItem(), com.uperto.smartmenu.SmartMenuOverlayView.getPainter(), com.uperto.smartmenu.SmartMenuActivity.mButton1, com.uperto.smartmenu.SmartMenuActivity.mButton2, com.uperto.smartmenu.SmartMenuActivity.mChangedBackgroundColor, com.uperto.smartmenu.SmartMenuActivity.mChangedHaloCenterColor, com.uperto.smartmenu.SmartMenuActivity.mChangedHaloGradient, com.uperto.smartmenu.SmartMenuActivity.mChangedHaloOutsideColor, com.uperto.smartmenu.SmartMenuActivity.mChangedHaloRadius, com.uperto.smartmenu.SmartMenuActivity.mChangedPainterColor, com.uperto.smartmenu.SmartMenuActivity.mChangedPainterStrokeWidth, com.uperto.smartmenu.SmartMenuActivity.mLibrary, com.uperto.smartmenu.SmartMenuActivity.mText, com.uperto.smartmenu.SmartMenuOverlayView.open(), com.uperto.smartmenu.SmartMenuOverlayView.setBackgroundColor(), com.uperto.smartmenu.SmartMenuOverlayView.setGestureLibrary(), com.uperto.smartmenu.SmartMenuOverlayView.setHaloCenterColor(), com.uperto.smartmenu.SmartMenuOverlayView.setHaloGradient(), com.uperto.smartmenu.SmartMenuOverlayView.setHaloOutsideColor(), and com.uperto.smartmenu.SmartMenuOverlayView.setHaloRadius().
void com.uperto.smartmenu.SmartMenuActivity.onSaveInstanceState (Bundle outState) [protected]
Definition at line 192 of file SmartMenuActivity.java.
Member Data Documentation
Button com.uperto.smartmenu.SmartMenuActivity.mButton1 [private]
Definition at line 35 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
Button com.uperto.smartmenu.SmartMenuActivity.mButton2 [private]
Definition at line 36 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
boolean com.uperto.smartmenu.SmartMenuActivity.mChangedBackgroundColor = false [private]
Definition at line 39 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
boolean com.uperto.smartmenu.SmartMenuActivity.mChangedHaloCenterColor = false [private]
Definition at line 42 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
boolean com.uperto.smartmenu.SmartMenuActivity.mChangedHaloGradient = false [private]
Definition at line 44 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
boolean com.uperto.smartmenu.SmartMenuActivity.mChangedHaloOutsideColor = false [private]
Definition at line 43 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
boolean com.uperto.smartmenu.SmartMenuActivity.mChangedHaloRadius = false [private]
Definition at line 45 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
boolean com.uperto.smartmenu.SmartMenuActivity.mChangedPainterColor = false [private]
Definition at line 40 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
boolean com.uperto.smartmenu.SmartMenuActivity.mChangedPainterStrokeWidth = false [private]
Definition at line 41 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
GestureLibrary com.uperto.smartmenu.SmartMenuActivity.mLibrary [private]
Definition at line 33 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
TextView com.uperto.smartmenu.SmartMenuActivity.mText [private]
Definition at line 34 of file SmartMenuActivity.java.
Referenced by com.uperto.smartmenu.SmartMenuActivity.onCreate().
The documentation for this class was generated from the following file:
src/com/uperto/smartmenu/SmartMenuActivity.java