SmartMenu: com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView Class Reference
com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView Class Reference
Inherits android::view::View.
Public Member Functions
SmartMenuCircleView (Context context, SmartMenuOverlayView parent)
boolean onTouchEvent (MotionEvent event)
boolean onKeyDown (int keyCode, KeyEvent event)
void onDraw (Canvas canvas)
void setText (String text)
String getText ()
Protected Member Functions
void init ()
void reset ()
void close ()
void setAnimationEnd ()
void addMenuItem (SmartMenuItem item)
SmartMenuItem getMenuItem (int index)
boolean deleteMenuItem (SmartMenuItem item)
void insertMenuItemAt (SmartMenuItem item, int index)
int indexOf (SmartMenuItem item)
Protected Attributes
float mHaloX = 0
float mHaloY = 0
boolean mDrawHalo = false
Private Member Functions
void drawBranch (Canvas canvas, int position, int length, SmartMenuItem icon)
void drawLabel (Canvas canvas, String text)
void drawHalo (Canvas canvas)
Private Attributes
int mCenterX
int mCenterY
int mCurrentAngle = 0
int mCurrentBranch = 0
int mCurrentBranchLength = 0
boolean mComputedValues = false
Paint mPainter
SmartMenuOverlayView mParent
String mText = null
Vector< SmartMenuItem > mItems
Detailed Description
Definition at line 303 of file SmartMenuOverlayView.java.
Constructor & Destructor Documentation
com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.SmartMenuCircleView (Context context, SmartMenuOverlayView parent)
Definition at line 319 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.init(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mParent.
Member Function Documentation
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.addMenuItem (SmartMenuItem item) [protected]
Definition at line 360 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.addMenuItem().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.close () [protected]
Definition at line 348 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mParent.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.close(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onKeyDown(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent().
boolean com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.deleteMenuItem (SmartMenuItem item) [protected]
Definition at line 368 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.deleteMenuItem().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch (Canvas canvas, int position, int length, SmartMenuItem icon) [private]
Definition at line 533 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.COS_45, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getIcon(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCenterX, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCenterY, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mPainter, com.uperto.smartmenu.SmartMenuOverlayView.sBranchesLength, com.uperto.smartmenu.SmartMenuOverlayView.sBranchesRadius, com.uperto.smartmenu.SmartMenuOverlayView.sCenterRadius, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setPosition(), and com.uperto.smartmenu.SmartMenuOverlayView.SIN_45.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo (Canvas canvas) [private]
Definition at line 615 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.mHaloCenterColor, com.uperto.smartmenu.SmartMenuOverlayView.mHaloGradient, com.uperto.smartmenu.SmartMenuOverlayView.mHaloOutsideColor, com.uperto.smartmenu.SmartMenuOverlayView.mHaloRadius, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mHaloX, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mHaloY, and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mParent.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawLabel (Canvas canvas, String text) [private]
Definition at line 605 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mPainter, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mText, com.uperto.smartmenu.SmartMenuOverlayView.sLabelFont, com.uperto.smartmenu.SmartMenuOverlayView.sLabelHeight, com.uperto.smartmenu.SmartMenuOverlayView.sLabelMargin, and com.uperto.smartmenu.SmartMenuOverlayView.sLabelWidth.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
SmartMenuItem com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.getMenuItem (int index) [protected]
Definition at line 364 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.getMenuItem().
String com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.getText ()
Definition at line 646 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mText.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent().
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.indexOf (SmartMenuItem item) [protected]
Definition at line 376 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.indexOf().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.init () [protected]
Definition at line 325 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mPainter, and com.uperto.smartmenu.SmartMenuOverlayView.setBackgroundColor().
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.SmartMenuCircleView().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.insertMenuItemAt (SmartMenuItem item, int index) [protected]
Definition at line 372 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.insertMenuItemAt().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw (Canvas canvas)
Definition at line 439 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawLabel(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCenterX, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCenterY, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mComputedValues, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentAngle, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentBranch, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentBranchLength, com.uperto.smartmenu.SmartMenuOverlayView.mDisplayHalo, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mDrawHalo, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mPainter, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mParent, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mText, com.uperto.smartmenu.SmartMenuOverlayView.sBranchesLength, com.uperto.smartmenu.SmartMenuOverlayView.sBranchesRadius, com.uperto.smartmenu.SmartMenuOverlayView.sCenterRadius, com.uperto.smartmenu.SmartMenuOverlayView.sCircleSpeed, com.uperto.smartmenu.SmartMenuOverlayView.sLabelFont, com.uperto.smartmenu.SmartMenuOverlayView.sLabelHeight, com.uperto.smartmenu.SmartMenuOverlayView.sLabelMargin, com.uperto.smartmenu.SmartMenuOverlayView.sLabelWidth, and com.uperto.smartmenu.SmartMenuOverlayView.sLineSpeed.
boolean com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onKeyDown (int keyCode, KeyEvent event)
Definition at line 431 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.close().
boolean com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent (MotionEvent event)
Definition at line 381 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.close(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.getText(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mDrawHalo, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mHaloX, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mHaloY, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems, com.uperto.smartmenu.SmartMenuOverlayView.sBranchesRadius, and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setText().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.reset () [protected]
Definition at line 339 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mComputedValues, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentAngle, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentBranch, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentBranchLength, and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setText().
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.open().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setAnimationEnd () [protected]
Definition at line 355 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentAngle, com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentBranch, and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.open().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setText (String text)
Definition at line 642 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mText.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.reset().
Member Data Documentation
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCenterX [private]
Definition at line 304 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCenterY [private]
Definition at line 304 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw().
boolean com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mComputedValues = false [private]
Definition at line 313 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.reset().
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentAngle = 0 [private]
Definition at line 305 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.reset(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setAnimationEnd().
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentBranch = 0 [private]
Definition at line 306 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.reset(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setAnimationEnd().
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mCurrentBranchLength = 0 [private]
Definition at line 307 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.reset().
boolean com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mDrawHalo = false [protected]
Definition at line 311 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent().
float com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mHaloX = 0 [protected]
Definition at line 309 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent().
float com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mHaloY = 0 [protected]
Definition at line 310 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent().
Vector<SmartMenuItem> com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mItems [private]
Definition at line 317 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.addMenuItem(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.deleteMenuItem(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.getMenuItem(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.indexOf(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.init(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.insertMenuItemAt(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onTouchEvent(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setAnimationEnd().
Paint com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mPainter [private]
Definition at line 314 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawLabel(), com.uperto.smartmenu.SmartMenuOverlayView.getPainter(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.init(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), and com.uperto.smartmenu.SmartMenuOverlayView.setPainter().
SmartMenuOverlayView com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mParent [private]
Definition at line 315 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.close(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawHalo(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.SmartMenuCircleView().
String com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.mText = null [private]
Definition at line 316 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawLabel(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.getText(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.onDraw(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.setText().
The documentation for this class was generated from the following file:
src/com/uperto/smartmenu/SmartMenuOverlayView.java