SmartMenu: com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem Class Reference
com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem Class Reference
Public Member Functions
SmartMenuItem (String text, Bitmap icon)
void setText (String text)
String getText ()
void setIcon (Bitmap icon)
Bitmap getIcon ()
void setPosition (int x, int y)
void setX (int mX)
int getX ()
void setY (int mY)
int getY ()
boolean onItemSelected ()
Private Attributes
String mText
Bitmap mIcon
int mX = 0
int mY = 0
Detailed Description
Definition at line 468 of file SmartMenuOverlayView.java.
Constructor & Destructor Documentation
com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.SmartMenuItem (String text, Bitmap icon)
Parameters:
text Text displayed
icon Bitmap displayed into the circle
Definition at line 478 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mText, and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setIcon().
Member Function Documentation
Bitmap com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getIcon ()
Returns:
Definition at line 507 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mIcon.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch().
String com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getText ()
Returns:
Definition at line 493 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mText.
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getX ()
Returns:
Definition at line 530 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mX.
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getY ()
Returns:
Definition at line 544 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mY.
boolean com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.onItemSelected ()
Definition at line 548 of file SmartMenuOverlayView.java.
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setIcon (Bitmap icon)
Parameters:
icon
Definition at line 500 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mIcon.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.SmartMenuItem().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setPosition (int x, int y)
Parameters:
x
y
Definition at line 515 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setX(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setY().
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuCircleView.drawBranch().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setText (String text)
Parameters:
text
Definition at line 486 of file SmartMenuOverlayView.java.
References com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mText.
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setX (int mX)
Parameters:
mX
Definition at line 523 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setPosition().
void com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setY (int mY)
Parameters:
mY
Definition at line 537 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setPosition().
Member Data Documentation
Bitmap com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mIcon [private]
Definition at line 470 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getIcon(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setIcon().
String com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mText [private]
Definition at line 469 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getText(), com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.setText(), and com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.SmartMenuItem().
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mX = 0 [private]
Definition at line 472 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getX().
int com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.mY = 0 [private]
Definition at line 472 of file SmartMenuOverlayView.java.
Referenced by com.uperto.smartmenu.SmartMenuOverlayView.SmartMenuItem.getY().
The documentation for this class was generated from the following file:
src/com/uperto/smartmenu/SmartMenuOverlayView.java